language: php

os:
  - linux

php:
  - 7.0
  - 7.1

matrix:
  include:
    - php: 7.0
      env: PHPSTAN=1
    - php: 7.1
      env: PHPSTAN=1

install:
    - composer self-update
    - composer install

script:
  - if [ "$PHPSTAN" = "1" ]; then vendor/bin/phpstan analyse src --level=7 --ansi --no-progress; fi
